check50:
  checks:
    hello world:
      - run: python3 hello.py
        stdout: Hello, world!
        exit: 0
    goodbye world:
      - run: python3 goodbye.py
        stdout: Goodbye, world!
        exit: 0
