check50:
  checks:
    hello world check:
      - run: python3 hello.py
        stdout: Hello, CS50 world!
        exit: 0
    goodbye world check:
      - run: python3 goodbye.py
        stdout: Goodbye, CS50 world!
        exit: 0
